language: node_js
node_js: 10
addons:
  apt:
    packages:
    - libgconf-2-4

install:
  - npm ci
  - npx lerna bootstrap
script:
  - npx lerna run build
  - npx lerna run lint
  - npx lerna run --scope dashboard test
  - npx lerna run --scope infra deploy:prod
  - npx lerna run --scope e2e test:prod